<a href="https://colab.research.google.com/github/jiyeonbeackuq/data-tutoring-sparta5/blob/main/python_basic_day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 문제 1
- Seaborn 라이브러리에서 제공하는 Diamond 데이터셋을 활용하여 다음을 수행하세요:
    - 1) x, y, z 중 하나라도 0인 데이터를 삭제하세요.
    - 2) x, y, z 를 곱해 'volume' 칼럼을 생성하세요.
    - 범주형 변수인 cut, color, clarity를 머신러닝 모델에 활용할 수 있도록 수치형으로 변환합니다.
    - **`cut`**: `Fair` = 1, `Good` = 2, `Very Good` = 3, `Premium` = 4, `Ideal` = 5로 인코딩하세요.
    - **`color`**: `E`, `I`, `J`, `H`, `F`, `G`, `D`를 각각 1부터 7로 인코딩하세요.
    - **`clarity`**:
        - `SI2`와 `SI1` → `1` (S 그룹),
        - `VS1`와 `VS2` → `2` (VS 그룹),
        - `VVS2`와 `VVS1` → `3` (VVS 그룹),
        - `I1`과 `IF` → `4` (I 그룹).

In [ ]:
# 코드1
import seaborn as sns
import pandas as pd

diamonds = sns.load_dataset("diamonds")

# Categorical -> String 변환
diamonds["cut"] = diamonds["cut"].astype(str)
diamonds["color"] = diamonds["color"].astype(str)
diamonds["clarity"] = diamonds["clarity"].astype(str)

In [ ]:
diamonds[(diamonds['x']!=0) & (diamonds['y']!=0) & (diamonds['z']!=0)]

,carat,cut,color,clarity,depth,table,price,x,y,z,volume
0,0.23,5,1,1,61.5,55.0,326,3.95,3.98,2.43,38.202030
1,0.21,4,1,1,59.8,61.0,326,3.89,3.84,2.31,34.505856
2,0.23,2,1,2,56.9,65.0,327,4.05,4.07,2.31,38.076885
3,0.29,4,2,2,62.4,58.0,334,4.20,4.23,2.63,46.724580
4,0.31,2,3,1,63.3,58.0,335,4.34,4.35,2.75,51.917250
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,5,7,1,60.8,57.0,2757,5.75,5.76,3.50,115.920000
53936,0.72,2,7,1,63.1,55.0,2757,5.69,5.75,3.61,118.110175
53937,0.70,3,7,1,62.8,60.0,2757,5.66,5.68,3.56,114.449728
53938,0.86,4,4,1,61.0,58.0,2757,6.15,6.12,3.74,140.766120
53939,0.75,5,7,1,62.2,55.0,2757,5.83,5.87,3.64,124.568444

In [ ]:
diamonds[~((diamonds['x']==0) | (diamonds['y']==0) | (diamonds['z']==0))]

,carat,cut,color,clarity,depth,table,price,x,y,z,volume
0,0.23,5,1,1,61.5,55.0,326,3.95,3.98,2.43,38.202030
1,0.21,4,1,1,59.8,61.0,326,3.89,3.84,2.31,34.505856
2,0.23,2,1,2,56.9,65.0,327,4.05,4.07,2.31,38.076885
3,0.29,4,2,2,62.4,58.0,334,4.20,4.23,2.63,46.724580
4,0.31,2,3,1,63.3,58.0,335,4.34,4.35,2.75,51.917250
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,5,7,1,60.8,57.0,2757,5.75,5.76,3.50,115.920000
53936,0.72,2,7,1,63.1,55.0,2757,5.69,5.75,3.61,118.110175
53937,0.70,3,7,1,62.8,60.0,2757,5.66,5.68,3.56,114.449728
53938,0.86,4,4,1,61.0,58.0,2757,6.15,6.12,3.74,140.766120
53939,0.75,5,7,1,62.2,55.0,2757,5.83,5.87,3.64,124.568444

In [ ]:
diamonds[~(diamonds['x'] * diamonds['y'] * diamonds['z'] == 0)]

,carat,cut,color,clarity,depth,table,price,x,y,z,volume
0,0.23,5,1,1,61.5,55.0,326,3.95,3.98,2.43,38.202030
1,0.21,4,1,1,59.8,61.0,326,3.89,3.84,2.31,34.505856
2,0.23,2,1,2,56.9,65.0,327,4.05,4.07,2.31,38.076885
3,0.29,4,2,2,62.4,58.0,334,4.20,4.23,2.63,46.724580
4,0.31,2,3,1,63.3,58.0,335,4.34,4.35,2.75,51.917250
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,5,7,1,60.8,57.0,2757,5.75,5.76,3.50,115.920000
53936,0.72,2,7,1,63.1,55.0,2757,5.69,5.75,3.61,118.110175
53937,0.70,3,7,1,62.8,60.0,2757,5.66,5.68,3.56,114.449728
53938,0.86,4,4,1,61.0,58.0,2757,6.15,6.12,3.74,140.766120
53939,0.75,5,7,1,62.2,55.0,2757,5.83,5.87,3.64,124.568444

In [ ]:
# x * y * z = 0 삭제
diamonds = diamonds[~((diamonds['x']==0) | (diamonds['y']==0) | (diamonds['z']==0))]

# volume column 만들기
diamonds['volume'] = diamonds['x'] * diamonds['y'] * diamonds['z']

# cut 인코딩
diamonds.loc[diamonds["cut"] == "Fair", "cut"] = 1
diamonds.loc[diamonds["cut"] == "Good", "cut"] = 2
diamonds.loc[diamonds["cut"] == "Very Good", "cut"] = 3
diamonds.loc[diamonds["cut"] == "Premium", "cut"] = 4
diamonds.loc[diamonds["cut"] == "Ideal", "cut"] = 5

# color 인코딩
diamonds.loc[diamonds["color"] == "E", "color"] = 1
diamonds.loc[diamonds["color"] == "I", "color"] = 2
diamonds.loc[diamonds["color"] == "J", "color"] = 3
diamonds.loc[diamonds["color"] == "H", "color"] = 4
diamonds.loc[diamonds["color"] == "F", "color"] = 5
diamonds.loc[diamonds["color"] == "G", "color"] = 6
diamonds.loc[diamonds["color"] == "D", "color"] = 7

# clarity 그룹화 및 인코딩
diamonds.loc[diamonds["clarity"].isin(["SI2", "SI1"]), "clarity"] = 1
diamonds.loc[diamonds["clarity"].isin(["VS1", "VS2"]), "clarity"] = 2
diamonds.loc[diamonds["clarity"].isin(["VVS2", "VVS1"]), "clarity"] = 3
diamonds.loc[diamonds["clarity"].isin(["I1", "IF"]), "clarity"] = 4

# 결과 출력
print(diamonds.shape)
print(diamonds.head())

(53920, 11)
   carat cut color  clarity  depth  table  price     x     y     z     volume
0   0.23   5     1        1   61.5   55.0    326  3.95  3.98  2.43  38.202030
1   0.21   4     1        1   59.8   61.0    326  3.89  3.84  2.31  34.505856
2   0.23   2     1        2   56.9   65.0    327  4.05  4.07  2.31  38.076885
3   0.29   4     2        2   62.4   58.0    334  4.20  4.23  2.63  46.724580
4   0.31   2     3        1   63.3   58.0    335  4.34  4.35  2.75  51.917250

In [ ]:
# 코드 2

import seaborn as sns
import pandas as pd

# 데이터 로드
diamonds = sns.load_dataset("diamonds")

# x * y * z = 0 삭제
diamonds = diamonds[~((diamonds['x']==0) | (diamonds['y']==0) | (diamonds['z']==0))]

# volume column 만들기
diamonds['volume'] = diamonds['x'] * diamonds['y'] * diamonds['z']

# cut 인코딩
diamonds["cut"] = diamonds["cut"].replace({
    "Fair": 1,
    "Good": 2,
    "Very Good": 3,
    "Premium": 4,
    "Ideal": 5
})

# color 인코딩
diamonds["color"] = diamonds["color"].replace({
    "E": 1,
    "I": 2,
    "J": 3,
    "H": 4,
    "F": 5,
    "G": 6,
    "D": 7
})

# clarity 그룹화 및 인코딩
diamonds["clarity"] = diamonds["clarity"].replace({
    "SI2": 1, "SI1": 1,  # S 그룹
    "VS1": 2, "VS2": 2,  # VS 그룹
    "VVS2": 3, "VVS1": 3,  # VVS 그룹
    "I1": 4, "IF": 4  # I 그룹
})

# 결과 출력
print(diamonds.shape)
print(diamonds.head())

(53920, 11)
   carat cut color clarity  depth  table  price     x     y     z     volume
0   0.23   5     1       1   61.5   55.0    326  3.95  3.98  2.43  38.202030
1   0.21   4     1       1   59.8   61.0    326  3.89  3.84  2.31  34.505856
2   0.23   2     1       2   56.9   65.0    327  4.05  4.07  2.31  38.076885
3   0.29   4     2       2   62.4   58.0    334  4.20  4.23  2.63  46.724580
4   0.31   2     3       1   63.3   58.0    335  4.34  4.35  2.75  51.917250

<ipython-input-5-d3b4a73e096d>:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  diamonds["cut"] = diamonds["cut"].replace({
<ipython-input-5-d3b4a73e096d>:16: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  diamonds["cut"] = diamonds["cut"].replace({
<ipython-input-5-d3b4a73e096d>:25: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  diamonds["color"] = diamonds["color"].replace({
<ipython-input-5-d3b4a73e096d>:25: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  diamonds["color"] = diamonds["color"].replace({
<ipython-input-5-d3b4a73e096d>:36: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  diamonds["clarity"] = diamonds["clarity"].replace({
<ipython-input-5-d3b4a73e096d>:36: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  diamonds["clarity"] = diamonds["clarity"].replace({

In [ ]:
import seaborn as sns
import pandas as pd

# 데이터 로드
diamonds = sns.load_dataset("diamonds")

# x * y * z = 0 삭제
diamonds = diamonds[~((diamonds['x']==0) | (diamonds['y']==0) | (diamonds['z']==0))]

# volume column 만들기
diamonds['volume'] = diamonds['x'] * diamonds['y'] * diamonds['z']

# cut 인코딩
cut_mapping = {"Fair": 1, "Good": 2, "Very Good": 3, "Premium": 4, "Ideal": 5}
diamonds["cut"] = diamonds["cut"].map(cut_mapping)

# color 인코딩
color_mapping = {"E": 1, "I": 2, "J": 3, "H": 4, "F": 5, "G": 6, "D": 7}
diamonds["color"] = diamonds["color"].map(color_mapping)

# clarity 그룹화 및 인코딩
clarity_mapping = {
    "SI2": 1, "SI1": 1,  # S 그룹
    "VS1": 2, "VS2": 2,  # VS 그룹
    "VVS2": 3, "VVS1": 3,  # VVS 그룹
    "I1": 4, "IF": 4  # I 그룹
}
diamonds["clarity"] = diamonds["clarity"].map(clarity_mapping)

# 결과 출력
print(diamonds.shape)
print(diamonds.head())

(53920, 11)
   carat cut color  clarity  depth  table  price     x     y     z     volume
0   0.23   5     1        1   61.5   55.0    326  3.95  3.98  2.43  38.202030
1   0.21   4     1        1   59.8   61.0    326  3.89  3.84  2.31  34.505856
2   0.23   2     1        2   56.9   65.0    327  4.05  4.07  2.31  38.076885
3   0.29   4     2        2   62.4   58.0    334  4.20  4.23  2.63  46.724580
4   0.31   2     3        1   63.3   58.0    335  4.34  4.35  2.75  51.917250

# map과 replace의 차이

In [ ]:
import pandas as pd

# 데이터 생성
df = pd.DataFrame({"cut": ["Fair", "Good", "Very Good","Excellent", "Premium", "Ideal"]})

# map을 사용하여 값 변환
cut_mapping = {"Fair": 1, "Good": 2, "Very Good": 3, "Premium": 4, "Ideal": 5}
df["cut_mapped"] = df["cut"].map(cut_mapping)

print(df)

         cut  cut_mapped
0       Fair         1.0
1       Good         2.0
2  Very Good         3.0
3  Excellent         NaN
4    Premium         4.0
5      Ideal         5.0

In [ ]:
# 데이터 생성
df = pd.DataFrame({"cut": ["Fair", "Good", "Very Good","Excellent", "Premium", "Ideal"]})

df["cut_replaced"] = df["cut"].replace({
    "Fair": 1,
    "Good": 2,
    "Very Good": 3,
    "Premium": 4,
    "Ideal": 5
})

print(df)

         cut cut_replaced
0       Fair            1
1       Good            2
2  Very Good            3
3  Excellent    Excellent
4    Premium            4
5      Ideal            5

# Day6 - 문제 2: 학생 성적 관리 시스템
* 다음 요구사항에 맞게 3개의 함수를 작성하세요.
* 요구사항:
** 학생들의 이름과 성적을 딕셔너리에 저장하고, 출력하는 함수를 작성하세요. (add_student(grades, name, score)
** 성적 평균을 반환하는 함수를 작성하세요. (calculate_average(grades))
** 최고 점수 학생을 반환하는 프로그램 작성하세요. (find_top_students(grades))
** 출력결과를 참고하여, 같은 양식으로 출력되도록 함수를 작성하세요.

* 힌트:
딕셔너리 자료형에서 max와 min값 구하는 방법에 대해 필요한 경우, 아래 링크를 참고하세요.
https://note.nkmk.me/en/python-dict-value-max-min/

In [ ]:
def add_student(grades, name, score):
    grades[name] = score
    print(f"Added {name} with score {score}.")

# Added Alice with score 85.

def calculate_average(grades):
    return sum(grades.values()) / len(grades)

def find_top_student(grades):
    top_student = max(grades, key=grades.get)
    return top_student, grades[top_student]

In [ ]:

# Example usage
grades = {}
add_student(grades, "Alice", 85)
add_student(grades, "Bob", 92)
add_student(grades, "Charlie", 78)

Added Alice with score 85.
Added Bob with score 92.
Added Charlie with score 78.

In [ ]:
grades

{'Alice': 85, 'Bob': 92, 'Charlie': 78}

In [ ]:
max(grades)

'Charlie'

In [ ]:
max(grades.values())

92

In [ ]:
max(grades, key=grades.get)

'Bob'

In [ ]:
print(f"Average score: {calculate_average(grades):.2f}")

Average score: 85.00



top_student, top_score = find_top_student(grades)
print(f"Top student: {top_student} with score {top_score}")

"""
Added Alice with score 85.
Added Bob with score 92.
Added Charlie with score 78.
Average score: 85.00
Top student: Bob with score 92
"""

In [ ]:
top_student, top_score = find_top_student(grades)
print(f"Top student: {top_student} with score {top_score}")

Top student: Bob with score 92